name: Dependency updates lookout

  # ┌────────────── second (optional)
  # │ ┌──────────── minute (0 - 59)
  # │ │ ┌────────── hour (0 - 23)
  # │ │ │ ┌──────── day of month (1 - 31)
  # │ │ │ │ ┌────── month (1 - 12)
  # │ │ │ │ │ ┌──── day of week (0 - 6)
  # │ │ │ │ │ │
  # │ │ │ │ │ │
  # * * * * * *

on:
  schedule:
    - cron: "0 3 1 * *"

jobs:

  display_dependency_updates:
    name: Check dependency updates
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 22
          check-latest: true
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Fetch updates
        run: ./gradlew --refresh-dependencies dependencyUpdates

      - name: Upload dependencies report
        uses: actions/upload-artifact@v4
        with:
          name: Yumi Retailer dependencies report
          path: app/build/reports