name: Generate AAB Release

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  JVM_OPTS: -Xmx2048m

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 22
          check-latest: true
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Decode keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo $ENCODED_KEYSTORE | base64 --decode > app/Noliaware.jks
          echo KEYSTORE=Noliaware.jks >> $GITHUB_ENV

      - name: Execute Gradle build
        run: ./gradlew build --warning-mode all

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Build app bundle release (AAB)
        run: ./gradlew app:bundleRelease

      - name: Set release date
        run: echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: Yumi Retailer APK - ${{ env.RELEASE_DATE }}
          path: app/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: Yumi Retailer AAB - ${{ env.RELEASE_DATE }}
          path: app/build/outputs/bundle/release/
